image:
    name: hashicorp/terraform:light
    entrypoint:
        - '/usr/bin/env'


before_script:
    - rm -rf .terraform 
    - terraform --version
    - terraform init 
    - apk update
    - apk add unzip
    - apk add curl python3 py3-pip
    - apk add aws-cli
    - curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
    - mv /tmp/eksctl /usr/local/bin
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl


stages:
    - configure
    - validate
    - plan 
    - apply
    - destroy


configure:
    stage: configure
    script:
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID 
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws configure set region $AWS_DEFAULT_REGION


validate:
    stage: validate 
    script:
        - terraform validate


plan:
    stage: plan 
    script:
        - set 
        - echo $AWS_SECRET_ACCESS_KEY
        - echo $AWS_ACCESS_KEY_ID
        - terraform plan 
    only: 
       - master     


apply:
    stage: apply
    script:
        - set 
        - echo $AWS_SECRET_ACCESS_KEY
        - echo $AWS_ACCESS_KEY_ID
        - terraform apply -auto-approve
    only:
        - master 

destroy:
    stage: destroy 
    script:
        - set 
        - echo $AWS_SECRET_ACCESS_KEY
        - echo $AWS_ACCESS_KEY_ID
        - terraform destroy --auto-approve
    when: manual     
    only: 
        - master 
        

