image:
    name: hashicorp/terraform:light
    entrypoint:
        - '/usr/bin/env'


before_script:
    - rm -rf .terraform 
    - terraform --version
    - terraform init 
    - apk update
    - apt-get install -y ansible

stages:
    - configure
    - validate
    - plan 
    - apply
    - ansible 
    - destroy


configure:
    stage: configure
    script:
        - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID 
        - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        - aws configure set region $AWS_DEFAULT_REGION


validate:
    stage: validate 
    script:
        - terraform validate


plan:
    stage: plan 
    script:
        - set 
        - echo $AWS_SECRET_ACCESS_KEY
        - echo $AWS_ACCESS_KEY_ID
        - terraform plan 
    only: 
       - master     


apply:
    stage: apply
    script:
        - set 
        - echo $AWS_SECRET_ACCESS_KEY
        - echo $AWS_ACCESS_KEY_ID
        - terraform apply -auto-approve
    only:
        - master 

ansible:
    script:
        - ANSIBLE_HOST_KEY_CHECKING=False  ansible-playbook -i host-inventory  project.yml

destroy:
    stage: destroy 
    script:
        - set 
        - echo $AWS_SECRET_ACCESS_KEY
        - echo $AWS_ACCESS_KEY_ID
        - terraform destroy --auto-approve
    when: manual     
    only: 
        - master 
        

