---
- name: set up the 3 instances
  hosts: all
  remote_user: ubuntu
  become: yes


  tasks:
  - name: update cache
    apt:
      update_cache: yes

  - name: install apache
    apt:
     name: apache2
     state: present

  - name: Start Apache
    service: name=apache2 state=started enabled=yes

  - name: set timezone to africa/lagos
    timezone:
     name: Africa/Lagos


  - name: remove default hmtl files from servers
    file:
     name: /var/www/html/index.html
     state: absent


  - name: Display hostname
    shell: echo "<h1>Hello world!! This is $(hostname -f) and the date is $(date)</h1>" >> /var/www/html/index.html



  - name: restart apache server
